app:
  pgURL: 'postgres://nmtnefejrxmeza:SSFkJbDstRCE2d1x4sMmUuvXiz@ec2-174-129-21-42.compute-1.amazonaws.com:5432/d585v5dia424sc'
  pg:
    database:
    username:
    password:
    host:
    dialect:
    port:
  port: 10010
  query:
    pageSize: 20
    onlyRootMessages: false